# Generated by Django 5.0 on 2023-12-20 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productcategory_product_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategory',
            new_name='Category',
        ),
    ]
