version: '3.9'

services:
  redis_db:
    image: "redis"
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - "redis_data_db:/data"

#  web_cmd:
#    build: .
#    command: python manager.py runserver 0.0.0.0:8000
#    volumes:
#      - .:/ht_23
#    ports:
#      - "8000:8000"
#    env_file:
#      - .env


  celery_woker:
    build: .
    command: celery -A apps worker -l INFO
    depends_on:
      - web_cmd
    env_file:
      - .env

volumes:
  redis_data_db:
