version: '3.8'

services:
  redis_db:
    image: "redis:5.0.1"
    ports:
      - "127.0.0.1:6379:6379"
#    volumes:
#      - "redis_data_db"
#
#
#  web_cmd:
#    build: .
#    command: python manage.py runserver 0.0.0.0:8000
#    volumes:
#      - .:/code
#    ports:
#      - "8000:8000"
#    env_file:
#      - .env
#
#
#  celery_woker:
#    build: .
#    command: celery -A apps worker --loglevel=INFO -P solo
#    volumes:
#      - .:/code
#    depends_on:
#      - web_cmd
#    env_file:
#      - .env
#
#volumes:
#  redis_data_db:
