version: '3.8'

services:
  redis_db:
    image: "redis:5.0.1"
    ports:
      - "127.0.0.1:6379:6379"
#    volumes:
#      - "redis_data_db"
# celery -A apps worker --loglevel=INFO -P solo

volumes:
  redis_data_db:
