# Generated by Django 5.0 on 2023-12-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('main_image_url', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('url', models.CharField(max_length=100)),
                ('regular_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('default_seller_id', models.CharField(max_length=100)),
                ('store_id', models.IntegerField()),
            ],
        ),
    ]
